import 'dart:convert';
import 'package:meta/meta.dart';

/// Wraps the ConsumerKey and ConsumerSecret provided by the Safaricom daraja apps, used to initialize the library too
class Header {
  /// Developers' Consumer Secret
  final String consumerSecret;

  /// Developers' Consumer Key
  final String consumerKey;

  /// An authentication secret automatically generated by [base64Encode] which returns a [String] of a [base64] digest of
  /// the [consumerKey] and [consumerSecret] and will be used as an Authorization header during authentication
  final String authSecret;
  Header({@required this.consumerKey, @required this.consumerSecret})
      : assert(consumerKey.isNotEmpty && consumerSecret.isNotEmpty),
        authSecret = base64Encode("$consumerKey:$consumerSecret".codeUnits);
}
